# Generated by Django 3.1.1 on 2020-10-11 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilingue_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('year', models.IntegerField(blank=True, max_length=4)),
                ('picture', models.CharField(blank=True, max_length=200)),
                ('media_type', models.CharField(choices=[('C', 'Cines'), ('L', 'Libros'), ('T', 'Programa de TV'), ('P', 'Podcasts'), ('M', 'Música')], default='C', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
