# Generated by Django 3.1.1 on 2020-10-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilingue_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
