# Generated by Django 3.1.1 on 2020-10-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilingue_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiste',
            name='configuración',
            field=models.CharField(blank=True, help_text='Setup in Spanish', max_length=500),
        ),
        migrations.AlterField(
            model_name='chiste',
            name='remate',
            field=models.CharField(blank=True, help_text='Punchline in Spanish', max_length=200),
        ),
        migrations.AlterField(
            model_name='chiste',
            name='título',
            field=models.CharField(help_text='Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='media',
            name='picture',
            field=models.CharField(blank=True, help_text='http link', max_length=250),
        ),
        migrations.AlterField(
            model_name='media',
            name='year',
            field=models.CharField(blank=True, help_text='2005', max_length=4),
        ),
    ]
