# Generated by Django 3.1.1 on 2020-10-13 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilingue_app', '0002_auto_20201013_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='picture',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bilingue_app.photo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
