# Generated by Django 3.1.1 on 2020-10-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilingue_app', '0002_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='year',
            field=models.IntegerField(blank=True),
        ),
    ]
