# Generated by Django 3.1.1 on 2020-10-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilingue_app', '0003_auto_20201011_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='is_streaming',
            field=models.BooleanField(default=True),
        ),
    ]
