# Generated by Django 3.1.1 on 2020-10-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilingue_app', '0003_auto_20201013_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='picture',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
