# Generated by Django 3.1.1 on 2020-10-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilingue_app', '0003_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='antonyms',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='cognates',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='english',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='spanish',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
