# Generated by Django 3.1.1 on 2020-10-11 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilingue_app', '0004_media_is_streaming'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='is_streaming',
        ),
    ]
