# Generated by Django 3.1.1 on 2020-10-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilingue_app', '0005_remove_media_is_streaming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
