# Generated by Django 3.1.1 on 2020-10-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilingue_app', '0006_auto_20201011_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chiste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(max_length=100)),
                ('foto', models.CharField(blank=True, max_length=200)),
                ('configuración', models.CharField(blank=True, max_length=500)),
                ('remate', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
