# Generated by Django 3.1.1 on 2020-10-12 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilingue_app', '0002_auto_20201012_1707'),
        ('bilingue_app', '0008_auto_20201012_1054'),
    ]

    operations = [
    ]
