# Generated by Django 3.1.1 on 2020-10-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilingue_app', '0009_merge_20201012_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiste',
            name='photos',
            field=models.ManyToManyField(to='bilingue_app.Photo'),
        ),
    ]
