# Generated by Django 3.1.1 on 2020-10-13 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilingue_app', '0011_auto_20201012_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
